// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE
'use strict';

var Sys = require("bsb-native/lib/js/sys.js");
var List = require("bsb-native/lib/js/list.js");
var $$Array = require("bsb-native/lib/js/array.js");
var $$String = require("bsb-native/lib/js/string.js");
var Caml_array = require("bsb-native/lib/js/caml_array.js");

var args = $$Array.sub(Sys.argv, 1, Sys.argv.length - 1 | 0);

function startWithDash(string) {
  return $$String.contains(string, /* "-" */45);
}

function arrGet(index, arr) {
  return Caml_array.caml_array_get(arr, index);
}

var flags = $$Array.of_list(List.filter(startWithDash)($$Array.to_list(args)));

function performFlagOperation(flag) {
  switch (flag) {
    case "-bytecode" : 
        return "Compiling to bytecode";
    case "-js" : 
        return "Compiling to js";
    case "-native" : 
        return "Compiling to native";
    default:
      return "Invalid compiler options";
  }
}

console.log(Caml_array.caml_array_get(args, 0));

console.log(performFlagOperation(Caml_array.caml_array_get(flags, 0)));

var test = "Hello World";

exports.args = args;
exports.startWithDash = startWithDash;
exports.arrGet = arrGet;
exports.flags = flags;
exports.performFlagOperation = performFlagOperation;
exports.test = test;
/* args Not a pure module */
